version: "3.8"

services:
  db:
    image: postgres:15
    container_name: devops-postgres
    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: devopsuser
      POSTGRES_PASSWORD: devopspassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: devops-flask
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: devopsdb
      DB_USER: devopsuser
      DB_PASSWORD: devopspassword
    depends_on:
      - db

volumes:
  postgres_data:
